### PR TITLE
Fixed a lot, went through and did a lot of optimizations.

### PR DESCRIPTION
**Pull request by sjohnson1021**
Apparently, the progressbar on the splash screen was doing something like the fibonacci sequence, just to look busy. That's gone. Splash screen comes up right away. Marquee Progress animation.. Fixed the app opening in the background.

Fixed the Global Delete methods.
Changed tabSource, added a seperate ProgressBar for scanning directory.

This was an all nighter, and then some. But I think it was worthwhile.

### CODE REVIEW

**Comment by sjohnson1021** [comment]
[bin.zip](https://github.com/AxionDrak/GameCube-Backup-Manager/files/9452932/bin.zip)

I'm going to let you test this out first before I merge this into main... Please and thank you?

**Comment by sjohnson1021** [comment]
> > [bin.zip](https://github.com/AxionDrak/GameCube-Backup-Manager/files/9452932/bin.zip)
> > 
> > I'm going to ask you guys to test this out first before I merge this into main... I did, several iterations of scenarios, installing, deleting, intentionally trying to break things. Could've/should've used unit tests, but..
> > 
> > Please and thank you? @laetemn @jmynes @Brycey92 @DDinghoya Ugh.. There are a some unforseen things, after sleeping (napping for an hour?) that didn't show in debugging. Back at it...
> 
> Yup! I'll test it today! :)

So, that build needed more work... I'll upload what I have here in a little bit.

**Thank you very much**, it's super helpful and encouraging to get fresh/other eyes to test and break things. 😁 

New build coming very soon.

**Comment by sjohnson1021** [comment]
> > [bin.zip](https://github.com/AxionDrak/GameCube-Backup-Manager/files/9452932/bin.zip)
> > I'm going to ask you guys to test this out first before I merge this into main... I did, several iterations of scenarios, installing, deleting, intentionally trying to break things. Could've/should've used unit tests, but..
> > Please and thank you? @laetemn @jmynes @Brycey92 @DDinghoya Ugh.. There are a some unforseen things, after sleeping (napping for an hour?) that didn't show in debugging. Back at it...
> 
> Yup! I'll test it today! :)

Sorry for the delay, wasted time having to backtrack because I didn't like the way some things were handled. This build should be testable. Might even just merge here in a day or two, barring anything major or based on feedback.
[sjohnson1021-gcbm-build-8-31-22.zip](https://github.com/AxionDrak/GameCube-Backup-Manager/files/9459217/sjohnson1021-gcbm-build-8-31-22.zip)

**Comment by alfonsojon** [comment]
I tested your build from today and can confirm I do not have the issue listed in #79

**Comment by sjohnson1021** [comment]
Alright, I'm going to take a break for .. now.. sleep and whatnot. I like where this is at, but please do continue to report issues as they arise. 

I'm aware that installing 1:1 , multiple files ( I tested a batch of 33) works, but locks the datagridview until you reload the list. Not ideal. and it's literally 1 line of code..

dgvSource.Enabled = true;

I just... Realllly. **_Reaaaaallly_** need sleep right now, and I don't want to risk ruining this progress, by doing something stupid.

Merging and dropping a release. Thanks again all, be back .. way too soon probably.
Screenshot 2022-09-01 011311

**Comment by DDinghoya** [comment]
I've been testing it for a short time and haven't had any major problems. :)

There are some translation issues, but it's a very minor issue.

You've worked hard and get plenty of rest.

**Pull request merged**
